import 'package:movies_app/core/utils/app_images.dart';
import 'package:movies_app/features/movie_details/movie_model.dart';

final List<MovieModel> genreMovies = [
  MovieModel(
    id: '1',
    title: 'Doctor Strange',
    posterImage: AppImages.movie1,
    year: '2022',
    genre: 'Action',
    summary:
        'Doctor Strange teams up with old and new mystical allies across the multiverse to confront a mysterious new adversary.',
    ageRating: '15',
    duration: '90',
    rating: 7.7,
    screenshots: [AppImages.movie1, AppImages.movie2, AppImages.movie3],
    similarMoviesID: [],
  ),
  MovieModel(
    id: '2',
    title: 'Doctor Strange',
    posterImage: AppImages.movie2,
    year: '2022',
    genre: 'Adventure',
    summary:
        'Doctor Strange teams up with old and new mystical allies across the multiverse to confront a mysterious new adversary.',
    ageRating: '15',
    duration: '90',
    rating: 7.7,
    screenshots: [AppImages.movie1, AppImages.movie2, AppImages.movie3],
    similarMoviesID: [],
  ),
  MovieModel(
    id: '3',
    title: 'Doctor Strange',
    posterImage: AppImages.movie3,
    year: '2022',
    genre: 'Animation',
    summary:
        'Doctor Strange teams up with old and new mystical allies across the multiverse to confront a mysterious new adversary.',
    ageRating: '15',
    duration: '90',
    rating: 7.7,
    screenshots: [AppImages.movie1, AppImages.movie2, AppImages.movie3],
    similarMoviesID: [],
  ),
  MovieModel(
    id: '4',
    title: 'Doctor Strange',
    posterImage: AppImages.movie1,
    year: '2022',
    genre: 'Drama',
    summary:
        'Doctor Strange teams up with old and new mystical allies across the multiverse to confront a mysterious new adversary.',
    ageRating: '15',
    duration: '90',
    rating: 7.7,
    screenshots: [AppImages.movie1, AppImages.movie2, AppImages.movie3],
    similarMoviesID: [],
  ),
  MovieModel(
    id: '5',
    title: 'Doctor Strange',
    posterImage: AppImages.movie2,
    year: '2022',
    genre: 'Comedy',
    summary:
        'Doctor Strange teams up with old and new mystical allies across the multiverse to confront a mysterious new adversary.',
    ageRating: '15',
    duration: '90',
    rating: 7.7,
    screenshots: [AppImages.movie1, AppImages.movie2, AppImages.movie3],
    similarMoviesID: [],
  ),
  MovieModel(
    id: '6',
    title: 'Doctor Strange',
    posterImage: AppImages.movie3,
    year: '2022',
    genre: 'Action',
    summary:
        'Doctor Strange teams up with old and new mystical allies across the multiverse to confront a mysterious new adversary.',
    ageRating: '15',
    duration: '90',
    rating: 7.7,
    screenshots: [AppImages.movie1, AppImages.movie2, AppImages.movie3],
    similarMoviesID: [],
  ),
  MovieModel(
    id: '7',
    title: 'Doctor Strange',
    posterImage: AppImages.movie1,
    year: '2022',
    genre: 'Action',
    summary:
        'Doctor Strange teams up with old and new mystical allies across the multiverse to confront a mysterious new adversary.',
    ageRating: '15',
    duration: '90',
    rating: 7.7,
    screenshots: [AppImages.movie1, AppImages.movie2, AppImages.movie3],
    similarMoviesID: [],
  ),
  MovieModel(
    id: '8',
    title: 'Doctor Strange',
    posterImage: AppImages.movie2,
    year: '2022',
    genre: 'Drama',
    summary:
        'Doctor Strange teams up with old and new mystical allies across the multiverse to confront a mysterious new adversary.',
    ageRating: '15',
    duration: '90',
    rating: 7.7,
    screenshots: [AppImages.movie1, AppImages.movie2, AppImages.movie3],
    similarMoviesID: [],
  ),
  MovieModel(
    id: '9',
    title: 'Doctor Strange',
    posterImage: AppImages.movie3,
    year: '2022',
    genre: 'Animation',
    summary:
        'Doctor Strange teams up with old and new mystical allies across the multiverse to confront a mysterious new adversary.',
    ageRating: '15',
    duration: '90',
    rating: 7.7,
    screenshots: [AppImages.movie1, AppImages.movie2, AppImages.movie3],
    similarMoviesID: [],
  ),
];
