// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf2wdIw01THKLWLiArtZ5ESybhQt261nc',
    appId: '1:194926913475:web:853c4dbd17abab167d3f76',
    messagingSenderId: '194926913475',
    projectId: 'movies-app-11021',
    authDomain: 'movies-app-11021.firebaseapp.com',
    storageBucket: 'movies-app-11021.firebasestorage.app',
    measurementId: 'G-V8XCP858R5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp1BV4jvcIankFdH7BS0QLdx564ki7eMo',
    appId: '1:194926913475:android:81167eec19c57ca77d3f76',
    messagingSenderId: '194926913475',
    projectId: 'movies-app-11021',
    storageBucket: 'movies-app-11021.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHg6wrLgMnjAMnfbZ4yXG6nu3FW3CS3kQ',
    appId: '1:194926913475:ios:ba4166db2c2a36b27d3f76',
    messagingSenderId: '194926913475',
    projectId: 'movies-app-11021',
    storageBucket: 'movies-app-11021.firebasestorage.app',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHg6wrLgMnjAMnfbZ4yXG6nu3FW3CS3kQ',
    appId: '1:194926913475:ios:ba4166db2c2a36b27d3f76',
    messagingSenderId: '194926913475',
    projectId: 'movies-app-11021',
    storageBucket: 'movies-app-11021.firebasestorage.app',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDf2wdIw01THKLWLiArtZ5ESybhQt261nc',
    appId: '1:194926913475:web:5dd196d692cd123d7d3f76',
    messagingSenderId: '194926913475',
    projectId: 'movies-app-11021',
    authDomain: 'movies-app-11021.firebaseapp.com',
    storageBucket: 'movies-app-11021.firebasestorage.app',
    measurementId: 'G-RL7VQRRZ6Y',
  );
}
